/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesDetailRouteImport } from './routes/updates-detail'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubsidiesDetailRouteImport } from './routes/subsidies-detail'
import { Route as SubsidiesRouteImport } from './routes/subsidies'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as MyconcernRouteImport } from './routes/myconcern'
import { Route as MessageAdminRouteImport } from './routes/message-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GrievanceRouteImport } from './routes/grievance'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EgovRouteImport } from './routes/egov'
import { Route as EditRouteImport } from './routes/edit'
import { Route as ConcernsRouteImport } from './routes/concerns'
import { Route as ChangeNumberRouteImport } from './routes/change-number'
import { Route as ApplyDetailRouteImport } from './routes/apply-detail'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRolesRouteImport } from './routes/admin-roles'
import { Route as AdminRejectRouteImport } from './routes/admin-reject'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVerifyRouteImport } from './routes/admin.verify'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminApplicationsDetailRouteImport } from './routes/admin.applications-detail'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'

const UpdatesDetailRoute = UpdatesDetailRouteImport.update({
  id: '/updates-detail',
  path: '/updates-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubsidiesDetailRoute = SubsidiesDetailRouteImport.update({
  id: '/subsidies-detail',
  path: '/subsidies-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const SubsidiesRoute = SubsidiesRouteImport.update({
  id: '/subsidies',
  path: '/subsidies',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const MyconcernRoute = MyconcernRouteImport.update({
  id: '/myconcern',
  path: '/myconcern',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageAdminRoute = MessageAdminRouteImport.update({
  id: '/message-admin',
  path: '/message-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievanceRoute = GrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EgovRoute = EgovRouteImport.update({
  id: '/egov',
  path: '/egov',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcernsRoute = ConcernsRouteImport.update({
  id: '/concerns',
  path: '/concerns',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeNumberRoute = ChangeNumberRouteImport.update({
  id: '/change-number',
  path: '/change-number',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyDetailRoute = ApplyDetailRouteImport.update({
  id: '/apply-detail',
  path: '/apply-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin-roles',
  path: '/admin-roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRejectRoute = AdminRejectRouteImport.update({
  id: '/admin-reject',
  path: '/admin-reject',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerifyRoute = AdminVerifyRouteImport.update({
  id: '/admin/verify',
  path: '/admin/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsDetailRoute = AdminApplicationsDetailRouteImport.update({
  id: '/admin/applications-detail',
  path: '/admin/applications-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-reject': typeof AdminRejectRoute
  '/admin-roles': typeof AdminRolesRoute
  '/apply': typeof ApplyRoute
  '/apply-detail': typeof ApplyDetailRoute
  '/change-number': typeof ChangeNumberRoute
  '/concerns': typeof ConcernsRoute
  '/edit': typeof EditRoute
  '/egov': typeof EgovRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grievance': typeof GrievanceRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/message-admin': typeof MessageAdminRoute
  '/myconcern': typeof MyconcernRoute
  '/otp': typeof OtpRoute
  '/password': typeof PasswordRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/subsidies': typeof SubsidiesRoute
  '/subsidies-detail': typeof SubsidiesDetailRoute
  '/terms': typeof TermsRoute
  '/updates': typeof UpdatesRoute
  '/updates-detail': typeof UpdatesDetailRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/applications-detail': typeof AdminApplicationsDetailRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-reject': typeof AdminRejectRoute
  '/admin-roles': typeof AdminRolesRoute
  '/apply': typeof ApplyRoute
  '/apply-detail': typeof ApplyDetailRoute
  '/change-number': typeof ChangeNumberRoute
  '/concerns': typeof ConcernsRoute
  '/edit': typeof EditRoute
  '/egov': typeof EgovRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grievance': typeof GrievanceRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/message-admin': typeof MessageAdminRoute
  '/myconcern': typeof MyconcernRoute
  '/otp': typeof OtpRoute
  '/password': typeof PasswordRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/subsidies': typeof SubsidiesRoute
  '/subsidies-detail': typeof SubsidiesDetailRoute
  '/terms': typeof TermsRoute
  '/updates': typeof UpdatesRoute
  '/updates-detail': typeof UpdatesDetailRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/applications-detail': typeof AdminApplicationsDetailRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-reject': typeof AdminRejectRoute
  '/admin-roles': typeof AdminRolesRoute
  '/apply': typeof ApplyRoute
  '/apply-detail': typeof ApplyDetailRoute
  '/change-number': typeof ChangeNumberRoute
  '/concerns': typeof ConcernsRoute
  '/edit': typeof EditRoute
  '/egov': typeof EgovRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grievance': typeof GrievanceRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/message-admin': typeof MessageAdminRoute
  '/myconcern': typeof MyconcernRoute
  '/otp': typeof OtpRoute
  '/password': typeof PasswordRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/subsidies': typeof SubsidiesRoute
  '/subsidies-detail': typeof SubsidiesDetailRoute
  '/terms': typeof TermsRoute
  '/updates': typeof UpdatesRoute
  '/updates-detail': typeof UpdatesDetailRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/applications-detail': typeof AdminApplicationsDetailRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-reject'
    | '/admin-roles'
    | '/apply'
    | '/apply-detail'
    | '/change-number'
    | '/concerns'
    | '/edit'
    | '/egov'
    | '/forgot-password'
    | '/grievance'
    | '/help'
    | '/home'
    | '/license'
    | '/login'
    | '/message-admin'
    | '/myconcern'
    | '/otp'
    | '/password'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/subsidies'
    | '/subsidies-detail'
    | '/terms'
    | '/updates'
    | '/updates-detail'
    | '/admin/applications'
    | '/admin/applications-detail'
    | '/admin/events'
    | '/admin/profile'
    | '/admin/support'
    | '/admin/verify'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-reject'
    | '/admin-roles'
    | '/apply'
    | '/apply-detail'
    | '/change-number'
    | '/concerns'
    | '/edit'
    | '/egov'
    | '/forgot-password'
    | '/grievance'
    | '/help'
    | '/home'
    | '/license'
    | '/login'
    | '/message-admin'
    | '/myconcern'
    | '/otp'
    | '/password'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/subsidies'
    | '/subsidies-detail'
    | '/terms'
    | '/updates'
    | '/updates-detail'
    | '/admin/applications'
    | '/admin/applications-detail'
    | '/admin/events'
    | '/admin/profile'
    | '/admin/support'
    | '/admin/verify'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin-reject'
    | '/admin-roles'
    | '/apply'
    | '/apply-detail'
    | '/change-number'
    | '/concerns'
    | '/edit'
    | '/egov'
    | '/forgot-password'
    | '/grievance'
    | '/help'
    | '/home'
    | '/license'
    | '/login'
    | '/message-admin'
    | '/myconcern'
    | '/otp'
    | '/password'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/subsidies'
    | '/subsidies-detail'
    | '/terms'
    | '/updates'
    | '/updates-detail'
    | '/admin/applications'
    | '/admin/applications-detail'
    | '/admin/events'
    | '/admin/profile'
    | '/admin/support'
    | '/admin/verify'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRejectRoute: typeof AdminRejectRoute
  AdminRolesRoute: typeof AdminRolesRoute
  ApplyRoute: typeof ApplyRoute
  ApplyDetailRoute: typeof ApplyDetailRoute
  ChangeNumberRoute: typeof ChangeNumberRoute
  ConcernsRoute: typeof ConcernsRoute
  EditRoute: typeof EditRoute
  EgovRoute: typeof EgovRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GrievanceRoute: typeof GrievanceRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  LicenseRoute: typeof LicenseRoute
  LoginRoute: typeof LoginRoute
  MessageAdminRoute: typeof MessageAdminRoute
  MyconcernRoute: typeof MyconcernRoute
  OtpRoute: typeof OtpRoute
  PasswordRoute: typeof PasswordRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SubsidiesRoute: typeof SubsidiesRoute
  SubsidiesDetailRoute: typeof SubsidiesDetailRoute
  TermsRoute: typeof TermsRoute
  UpdatesRoute: typeof UpdatesRoute
  UpdatesDetailRoute: typeof UpdatesDetailRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminApplicationsDetailRoute: typeof AdminApplicationsDetailRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminVerifyRoute: typeof AdminVerifyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates-detail': {
      id: '/updates-detail'
      path: '/updates-detail'
      fullPath: '/updates-detail'
      preLoaderRoute: typeof UpdatesDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subsidies-detail': {
      id: '/subsidies-detail'
      path: '/subsidies-detail'
      fullPath: '/subsidies-detail'
      preLoaderRoute: typeof SubsidiesDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subsidies': {
      id: '/subsidies'
      path: '/subsidies'
      fullPath: '/subsidies'
      preLoaderRoute: typeof SubsidiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myconcern': {
      id: '/myconcern'
      path: '/myconcern'
      fullPath: '/myconcern'
      preLoaderRoute: typeof MyconcernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message-admin': {
      id: '/message-admin'
      path: '/message-admin'
      fullPath: '/message-admin'
      preLoaderRoute: typeof MessageAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievance': {
      id: '/grievance'
      path: '/grievance'
      fullPath: '/grievance'
      preLoaderRoute: typeof GrievanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egov': {
      id: '/egov'
      path: '/egov'
      fullPath: '/egov'
      preLoaderRoute: typeof EgovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerns': {
      id: '/concerns'
      path: '/concerns'
      fullPath: '/concerns'
      preLoaderRoute: typeof ConcernsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-number': {
      id: '/change-number'
      path: '/change-number'
      fullPath: '/change-number'
      preLoaderRoute: typeof ChangeNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-detail': {
      id: '/apply-detail'
      path: '/apply-detail'
      fullPath: '/apply-detail'
      preLoaderRoute: typeof ApplyDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-roles': {
      id: '/admin-roles'
      path: '/admin-roles'
      fullPath: '/admin-roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-reject': {
      id: '/admin-reject'
      path: '/admin-reject'
      fullPath: '/admin-reject'
      preLoaderRoute: typeof AdminRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verify': {
      id: '/admin/verify'
      path: '/admin/verify'
      fullPath: '/admin/verify'
      preLoaderRoute: typeof AdminVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications-detail': {
      id: '/admin/applications-detail'
      path: '/admin/applications-detail'
      fullPath: '/admin/applications-detail'
      preLoaderRoute: typeof AdminApplicationsDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRejectRoute: AdminRejectRoute,
  AdminRolesRoute: AdminRolesRoute,
  ApplyRoute: ApplyRoute,
  ApplyDetailRoute: ApplyDetailRoute,
  ChangeNumberRoute: ChangeNumberRoute,
  ConcernsRoute: ConcernsRoute,
  EditRoute: EditRoute,
  EgovRoute: EgovRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GrievanceRoute: GrievanceRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  LicenseRoute: LicenseRoute,
  LoginRoute: LoginRoute,
  MessageAdminRoute: MessageAdminRoute,
  MyconcernRoute: MyconcernRoute,
  OtpRoute: OtpRoute,
  PasswordRoute: PasswordRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SubsidiesRoute: SubsidiesRoute,
  SubsidiesDetailRoute: SubsidiesDetailRoute,
  TermsRoute: TermsRoute,
  UpdatesRoute: UpdatesRoute,
  UpdatesDetailRoute: UpdatesDetailRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminApplicationsDetailRoute: AdminApplicationsDetailRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminVerifyRoute: AdminVerifyRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
